/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

export * from './user';
export * from './post';
export { getQueryKey } from '@zenstackhq/tanstack-query/runtime-v5';
export { VueQueryContextKey, provideHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
export { default as metadata } from './__model_meta';
