/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const PostScalarFieldEnumSchema = z.enum(["id", "createdAt", "updatedAt", "title", "content", "published", "authorId"])
