/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const UserScalarFieldEnumSchema = z.enum(["id", "name", "email", "emailVerified", "image", "createdAt", "updatedAt"])
